---
title: "Photographic_Bleaching"
author: "HM Putnam"
edited by: "HM Putnam"
date: "8/03/2024"
output:
  html_document: default
  pdf_document: default
---

# Loading in required libraries. 
```{r, include=FALSE}
library("vegan")
library("tidyverse")
library("lme4")
library("plotrix")
if ("EnvStats" %in% rownames(installed.packages()) == 'FALSE') install.packages('EnvStats') 
library("EnvStats")
library("car")
library("MuMIn")
if ("ggstatsplot" %in% rownames(installed.packages()) == 'FALSE') install.packages('ggstatsplot') 
library("ggstatsplot")

```

# Reading in quality controlled color data.
```{r}
Data <- read.csv("data/Color_Score_example.csv", header=T, sep=",", na.string="NA") #read in data file
#Data <-na.omit(Data) # removing all rows with NA values
Data$SP.Time.ID <- paste0(Data$Sample.id, "_",Data$Date, "_", Data$Treatment)# generating a grouping factor

#make photo.date a factor
Data$Date = as.factor(Data$Date)

```

Normalize coral color to color standards. 
```{r}
Data$Red.Norm.Coral <- Data$Red.Coral/Data$Red.Standard #normalize to standard
Data$Green.Norm.Coral <- Data$Green.Coral/Data$Green.Standard #normalize to standard
Data$Blue.Norm.Coral <- Data$Blue.Coral/Data$Blue.Standard #normalize to standard
```

# Principal components analysis to reduce color score to single value representing the majority of the variance
```{r}

score <- Data %>% select("Sample.id", "Species", "Treatment","SP.Time.ID", "Tank_Number", "Date",  "Red.Norm.Coral","Green.Norm.Coral", "Blue.Norm.Coral") #select columns from dataframe

blch.scor <- score  %>% select("Red.Norm.Coral","Green.Norm.Coral", "Blue.Norm.Coral") #subset dataframe for score matrix only

blch.scor <- as.matrix(blch.scor) #create matrix
rownames(blch.scor) <- score$SP.Time.ID #name columns in matrix

dist <- vegdist(blch.scor, method="euclidean") #calculate distance matrix of color scores

PCA.color <- princomp(dist) #run principal components analysis
PCA.color # view variance explained by PCs

Blch <- as.data.frame(-PCA.color$scores[,1]) #extract PC1
Blch$SP.Time.ID <- rownames(blch.scor) # add the sample names to the bleahcing score

Blch  <- left_join(Blch, Data, by="SP.Time.ID") #make a dataframe of PC1 and experiment factors
colnames(Blch) #view column names
names(Blch)[1] <- "Bleaching.Score" #name column

hist(Blch$Bleaching.Score)

```

# Plot data for outliers and Write out Color Score dataframe 
```{r}

Blch.meanse <- Blch %>% group_by(Species, Treatment, Date) %>% #group data by factors
  summarise(mean = mean(Bleaching.Score), #calculate mean by group
            sem = std.error(Bleaching.Score)) #calculate sem by group


cols <- c("darkblue", "red3", "gray") #set colors

pdf("output/colorscore_with_outliers_colonies.pdf")
Blch_plot1 <- ggplot(Blch.meanse, aes(x=Date, y = mean, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() + #plot points and lines
  geom_errorbar(aes(ymin=mean-sem, ymax=mean+sem), width=.2) + #plot sem error bars
  scale_color_manual(values = cols) + #color points
  facet_grid(~Species, scales = "free") + #facet by Species
  xlab("Timepoint") + #label x axis
  ylab("Color Score") + # label y axis
  theme_classic() + #set theme
  theme(legend.text = element_text(size = 7)) + #set legend text size
  theme(legend.title = element_text(size = 9)) + #set legend text title size
  geom_vline(xintercept = c(7.8), colour="black", linetype="dotted") + #add vertical line
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) +  #set font
  #scale_x_discrete(breaks = c("Week1", "Week2", "Week4", "Week6", "Week8", "Week12", "Week16"), labels = c("1 week", "2 week", "4 week", "6 week", "8 week", "12 week", "16 week")) + #set breaks
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(), #set theme
  panel.grid.major = element_blank(),  #set theme
  panel.grid.minor = element_blank(),  #set theme
  # Change axis line
  axis.line = element_line(colour = "black")) 
Blch_plot1 #view plot
dev.off()

Blch_plot1


```
